<?php

/**
 * Squads keyed like frontend TEAMS (real_madrid, vinotinto).
 * Each team: metadata + starters/bench. Player rows mirror `players` migration fields
 * plus squad keys: ref, number, moved, position (GK|DF|MF|FW → position_id when seeding).
 */

return [
    'real-madrid' => [
        [
            'name' => 'Thibaut',
            'lastname' => 'Courtois',
            'nickname' => 'La Jirafa',
            'slug' => 'thibaut-courtois',
            'code' => 'BEL',
            'photo' => 'courtois.jpg',
            'date_of_birth' => '1992-05-11',
            'nationality' => 'Belga',
            'height' => 200,
            'weight' => 96,
            'foot' => 'Left',
            'position' => 'GK',
            'number' => 1,
            'moved' => false,
        ],
        [
            'name' => 'Daniel',
            'lastname' => 'Carvajal',
            'nickname' => 'Carva',
            'slug' => 'dani-carvajal',
            'code' => 'ESP',
            'photo' => 'carvajal.jpg',
            'date_of_birth' => '1992-01-11',
            'nationality' => 'Española',
            'height' => 173,
            'weight' => 73,
            'foot' => 'Right',
            'position' => 'DF',
            'number' => 2,
            'moved' => false,
        ],
        [
            'name' => 'Éder',
            'lastname' => 'Militão',
            'nickname' => null,
            'slug' => 'eder-militao',
            'code' => 'BRA',
            'photo' => 'militao.jpg',
            'date_of_birth' => '1998-01-18',
            'nationality' => 'Brasileña',
            'height' => 186,
            'weight' => 78,
            'foot' => 'Right',
            'position' => 'DF',
            'number' => 3,
            'moved' => false,
        ],
        [
            'name' => 'David',
            'lastname' => 'Alaba',
            'nickname' => null,
            'slug' => 'david-alaba',
            'code' => 'AUT',
            'photo' => 'alaba.jpg',
            'date_of_birth' => '1992-06-24',
            'nationality' => 'Austriaca',
            'height' => 180,
            'weight' => 78,
            'foot' => 'Left',
            'position' => 'DF',
            'number' => 4,
            'moved' => false,
        ],
        [
            'name' => 'Fran',
            'lastname' => 'García',
            'nickname' => null,
            'slug' => 'fran-garcia',
            'code' => 'ESP',
            'photo' => 'fran-garcia.jpg',
            'date_of_birth' => '1999-08-14',
            'nationality' => 'Española',
            'height' => 169,
            'weight' => 69,
            'foot' => 'Left',
            'position' => 'DF',
            'number' => 20,
            'moved' => false,
        ],
        [
            'name' => 'Aurélien',
            'lastname' => 'Tchouaméni',
            'nickname' => null,
            'slug' => 'aurelien-tchouameni',
            'code' => 'FRA',
            'photo' => 'tchouameni.jpg',
            'date_of_birth' => '2000-01-27',
            'nationality' => 'Francesa',
            'height' => 187,
            'weight' => 81,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 18,
            'moved' => false,
        ],
        [
            'name' => 'Toni',
            'lastname' => 'Kroos',
            'nickname' => 'El Sniper',
            'slug' => 'toni-kroos',
            'code' => 'GER',
            'photo' => 'kroos.jpg',
            'date_of_birth' => '1990-01-04',
            'nationality' => 'Alemana',
            'height' => 183,
            'weight' => 76,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 8,
            'moved' => false,
        ],
        [
            'name' => 'Federico',
            'lastname' => 'Valverde',
            'nickname' => 'El Halcón',
            'slug' => 'fede-valverde',
            'code' => 'URU',
            'photo' => 'valverde.jpg',
            'date_of_birth' => '1998-07-22',
            'nationality' => 'Uruguaya',
            'height' => 182,
            'weight' => 78,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 15,
            'moved' => false,
        ],
        [
            'name' => 'Jude',
            'lastname' => 'Bellingham',
            'nickname' => 'Belligol',
            'slug' => 'jude-bellingham',
            'code' => 'ENG',
            'photo' => 'bellingham.jpg',
            'date_of_birth' => '2003-06-29',
            'nationality' => 'Inglesa',
            'height' => 186,
            'weight' => 75,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 5,
            'moved' => false,
        ],
        [
            'name' => 'Vinícius',
            'lastname' => 'Júnior',
            'nickname' => 'Vini',
            'slug' => 'vinicius-jr',
            'code' => 'BRA',
            'photo' => 'vini.jpg',
            'date_of_birth' => '2000-07-12',
            'nationality' => 'Brasileña',
            'height' => 176,
            'weight' => 73,
            'foot' => 'Right',
            'position' => 'FW',
            'number' => 7,
            'moved' => false,
        ],
        [
            'name' => 'Rodrygo',
            'lastname' => 'Goes',
            'nickname' => 'El Rayo',
            'slug' => 'rodrygo-goes',
            'code' => 'BRA',
            'photo' => 'rodrygo.jpg',
            'date_of_birth' => '2001-01-09',
            'nationality' => 'Brasileña',
            'height' => 174,
            'weight' => 64,
            'foot' => 'Right',
            'position' => 'FW',
            'number' => 11,
            'moved' => false,
        ],
        [
            'name' => 'Andriy',
            'lastname' => 'Lunin',
            'nickname' => null,
            'slug' => 'andriy-lunin',
            'code' => 'UKR',
            'photo' => 'lunin.jpg',
            'date_of_birth' => '1999-02-11',
            'nationality' => 'Ucraniana',
            'height' => 191,
            'weight' => 80,
            'foot' => 'Right',
            'position' => 'GK',
            'number' => 13,
            'moved' => false,
        ],
        [
            'name' => 'Trent',
            'lastname' => 'Alexander-Arnold',
            'nickname' => 'TAA',
            'slug' => 'trent-alexander-arnold',
            'code' => 'ENG',
            'photo' => 'trent.jpg',
            'date_of_birth' => '1998-10-07',
            'nationality' => 'Inglesa',
            'height' => 180,
            'weight' => 72,
            'foot' => 'Right',
            'position' => 'DF',
            'number' => 66,
            'moved' => false,
        ],
        [
            'name' => 'Arda',
            'lastname' => 'Güler',
            'nickname' => 'El Diamante Turco',
            'slug' => 'arda-guler',
            'code' => 'TUR',
            'photo' => 'guler.jpg',
            'date_of_birth' => '2005-02-25',
            'nationality' => 'Turca',
            'height' => 175,
            'weight' => 70,
            'foot' => 'Left',
            'position' => 'MF',
            'number' => 15,
            'moved' => false,
        ],
    ],
    'vinotinto' => [
        [
            'name' => 'Rafael',
            'lastname' => 'Romo',
            'nickname' => null,
            'slug' => 'rafael-romo',
            'code' => 'VEN',
            'photo' => 'romo.jpg',
            'date_of_birth' => '1990-02-25',
            'nationality' => 'Venezolana',
            'height' => 197,
            'weight' => 91,
            'foot' => 'Right',
            'position' => 'GK',
            'number' => 22,
            'moved' => false,
        ],
        [
            'name' => 'Alexander',
            'lastname' => 'González',
            'nickname' => null,
            'slug' => 'alexander-gonzalez',
            'code' => 'VEN',
            'photo' => 'alexander.jpg',
            'date_of_birth' => '1992-09-13',
            'nationality' => 'Venezolana',
            'height' => 178,
            'weight' => 74,
            'foot' => 'Right',
            'position' => 'DF',
            'number' => 4,
            'moved' => false,
        ],
        [
            'name' => 'Yordan',
            'lastname' => 'Osorio',
            'nickname' => null,
            'slug' => 'yordan-osorio',
            'code' => 'VEN',
            'photo' => 'osorio.jpg',
            'date_of_birth' => '1994-05-10',
            'nationality' => 'Venezolana',
            'height' => 186,
            'weight' => 81,
            'foot' => 'Right',
            'position' => 'DF',
            'number' => 2,
            'moved' => false,
        ],
        [
            'name' => 'Nahuel',
            'lastname' => 'Ferraresi',
            'nickname' => null,
            'slug' => 'nahuel-ferraresi',
            'code' => 'VEN',
            'photo' => 'ferraresi.jpg',
            'date_of_birth' => '1998-11-19',
            'nationality' => 'Venezolana',
            'height' => 190,
            'weight' => 84,
            'foot' => 'Right',
            'position' => 'DF',
            'number' => 3,
            'moved' => false,
        ],
        [
            'name' => 'Miguel',
            'lastname' => 'Navarro',
            'nickname' => null,
            'slug' => 'miguel-navarro',
            'code' => 'VEN',
            'photo' => 'navarro.jpg',
            'date_of_birth' => '1999-02-26',
            'nationality' => 'Venezolana',
            'height' => 174,
            'weight' => 69,
            'foot' => 'Left',
            'position' => 'DF',
            'number' => 15,
            'moved' => false,
        ],
        [
            'name' => 'José',
            'lastname' => 'Martínez',
            'nickname' => 'El Brujo',
            'slug' => 'jose-brujo-martinez',
            'code' => 'VEN',
            'photo' => 'brujo.jpg',
            'date_of_birth' => '1994-08-07',
            'nationality' => 'Venezolana',
            'height' => 175,
            'weight' => 70,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 13,
            'moved' => false,
        ],
        [
            'name' => 'Yangel',
            'lastname' => 'Herrera',
            'nickname' => null,
            'slug' => 'yangel-herrera',
            'code' => 'VEN',
            'photo' => 'herrera.jpg',
            'date_of_birth' => '1998-01-07',
            'nationality' => 'Venezolana',
            'height' => 184,
            'weight' => 82,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 6,
            'moved' => false,
        ],
        [
            'name' => 'Telasco',
            'lastname' => 'Segovia',
            'nickname' => null,
            'slug' => 'telasco-segovia',
            'code' => 'VEN',
            'photo' => 'segovia.jpg',
            'date_of_birth' => '2003-04-02',
            'nationality' => 'Venezolana',
            'height' => 180,
            'weight' => 74,
            'foot' => 'Right',
            'position' => 'MF',
            'number' => 20,
            'moved' => false,
        ],
        [
            'name' => 'Yeferson',
            'lastname' => 'Soteldo',
            'nickname' => 'Soteldinho',
            'slug' => 'yeferson-soteldo',
            'code' => 'VEN',
            'photo' => 'soteldo.jpg',
            'date_of_birth' => '1997-06-30',
            'nationality' => 'Venezolana',
            'height' => 160,
            'weight' => 65,
            'foot' => 'Right',
            'position' => 'FW',
            'number' => 10,
            'moved' => false,
        ],
        [
            'name' => 'Jefferson',
            'lastname' => 'Savarino',
            'nickname' => 'Savagol',
            'slug' => 'jefferson-savarino',
            'code' => 'VEN',
            'photo' => 'savarino.jpg',
            'date_of_birth' => '1996-11-11',
            'nationality' => 'Venezolana',
            'height' => 169,
            'weight' => 62,
            'foot' => 'Right',
            'position' => 'FW',
            'number' => 7,
            'moved' => false,
        ],
        [
            'name' => 'Salomón',
            'lastname' => 'Rondón',
            'nickname' => 'El Gladiador',
            'slug' => 'salomon-rondon',
            'code' => 'VEN',
            'photo' => 'rondon.jpg',
            'date_of_birth' => '1989-09-16',
            'nationality' => 'Venezolana',
            'height' => 186,
            'weight' => 86,
            'foot' => 'Right',
            'position' => 'FW',
            'number' => 23,
            'moved' => false,
        ],
    ],
];
